PROGRAM=program
all:$(PROGRAM)
program:
	gcc main.c -o program
clean:
	rm -rf program
test1:
	./program inputfilenum.txt -u -r -n -o outputfile.txt
test2:
	./program inputfile.txt -u -r -o outputfile.txt